apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/app-sre/python-project-template?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "20"
    pipelinesascode.tekton.dev/on-cel-expression: (event == "pull_request" && target_branch == "main") || (event == "push" && target_branch.startsWith("gh-readonly-queue/main/"))
  labels:
    appstudio.openshift.io/application: python-project-template-main
    appstudio.openshift.io/component: python-project-template-main
    pipelines.appstudio.openshift.io/type: build
  name: python-project-template-main-on-pull-request
  namespace: app-sre-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/app-sre-tenant/python-project-template-main/python-project-template-main:on-pr-{{revision}}
  - name: image-expires-after
    value: 1d
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: .
  - name: target-stage
    value: test
  - name: build-platforms
    value:
    - linux/x86_64
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/app-sre/shared-pipelines
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/multi-arch-build-pipeline.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-python-project-template-main
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
