apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/app-sre/{{ cookiecutter.project_slug }}?rev={%- raw %}{{revision}}{%- endraw %}
    build.appstudio.redhat.com/commit_sha: {%- raw %}'{{revision}}'{%- endraw %}
    build.appstudio.redhat.com/target_branch: {%- raw %}'{{target_branch}}'{%- endraw %}
    pipelinesascode.tekton.dev/max-keep-runs: "20"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  labels:
    appstudio.openshift.io/application: {{ cookiecutter.project_slug }}-main
    appstudio.openshift.io/component: {{ cookiecutter.project_slug }}-main
    pipelines.appstudio.openshift.io/type: build
  name: {{ cookiecutter.project_slug }}-main-on-push
  namespace: app-sre-tenant
spec:
  params:
  - name: git-url
    value: {%- raw %}'{{source_url}}'{%- endraw %}
  - name: revision
    value: {%- raw %}'{{revision}}'{%- endraw %}
  - name: output-image
    value: quay.io/redhat-user-workloads/app-sre-tenant/{{ cookiecutter.project_slug }}-main/{{ cookiecutter.project_slug }}-main:{%- raw %}{{revision}}{%- endraw %}
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: .
  - name: target-stage
{%- if cookiecutter.deployment == 'openshift' %}
    value: prod
{%- endif %}
{%- if cookiecutter.deployment == 'pypi' %}
    value: pypi
{%- endif %}
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/app-sre/shared-pipelines
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/multi-arch-build-pipeline.yaml
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-auth
    secret:
      secretName: {%- raw %}'{{ git_auth_secret }}'{%- endraw %}
{%- if cookiecutter.deployment == 'pypi' %}
  - name: pypi-auth
    secret:
      secretName: 'pypi-auth'
{%- endif %}
